const actions = {

    // LOGIN
    LOGIN_INPUT_CHANGE_MAIL: 'LOGIN_INPUT_CHANGE_MAIL',
    LOGIN_INPUT_CHANGE_PASSWORD: 'LOGIN_INPUT_CHANGE_PASSWORD',

    // REGISTER
    REGISTER_INPUT_CHANGE_MAIL: 'REGISTER_INPUT_CHANGE_MAIL',
    REGISTER_INPUT_CHANGE_NAME: 'REGISTER_INPUT_CHANGE_NAME',
    REGISTER_INPUT_CHANGE_PASSWORD: 'REGISTER_INPUT_CHANGE_PASSWORD',
    REGISTER_INPUT_CHANGE_REPEAT_PASSWORD: 'REGISTER_INPUT_CHANGE_REPEAT_PASSWORD'

};

export default actions;
