const actions = {

    // COMMON
    COMMON_SET_USER_DATA: 'COMMON_SET_USER_DATA',
    COMMON_SET_TITLE: 'COMMON_SET_TITLE',
    COMMON_ADD_GLOBAL_ERROR: 'COMMON_ADD_GLOBAL_ERROR',
    COMMON_CLEAR_GLOBAL_ERRORS: 'COMMON_CLEAR_GLOBAL_ERRORS',
    COMMON_NAUTH_DISABLED: 'COMMON_NAUTH_DISABLED',

    // LOGIN
    LOGIN_INPUT_CHANGE_MAIL: 'LOGIN_INPUT_CHANGE_MAIL',
    LOGIN_INPUT_CHANGE_PASSWORD: 'LOGIN_INPUT_CHANGE_PASSWORD',
    LOGIN_SET_SERVER_ERRORS: 'LOGIN_SET_SERVER_ERRORS',

    // REGISTER
    REGISTER_INPUT_CHANGE_MAIL: 'REGISTER_INPUT_CHANGE_MAIL',
    REGISTER_INPUT_CHANGE_NAME: 'REGISTER_INPUT_CHANGE_NAME',
    REGISTER_INPUT_CHANGE_PASSWORD: 'REGISTER_INPUT_CHANGE_PASSWORD',
    REGISTER_INPUT_CHANGE_REPEAT_PASSWORD: 'REGISTER_INPUT_CHANGE_REPEAT_PASSWORD',
    REGISTER_SET_SERVER_ERRORS: 'REGISTER_SET_SERVER_ERRORS',
    REGISTER_SET_CURRENT_STEP: 'REGISTER_SET_CURRENT_STEP',

    // RESET
    RESET_INPUT_CHANGE_MAIL: 'RESET_INPUT_CHANGE_MAIL',
    RESET_SET_SERVER_ERRORS: 'RESET_SET_SERVER_ERRORS',
    RESET_SET_CURRENT_STEP: 'RESET_SET_CURRENT_STEP'

};

export default actions;
